/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/platform/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập bằng tên đăng nhập và mật khẩu, nhận access token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách kỳ thu, mới nhất trước; có date thì chỉ các kỳ chứa ngày đó */
        get: operations["list"];
        put?: never;
        /** Mở kỳ thu tháng/quý (quản trị); gắn biểu giá có hiệu lực tại ngày đầu kỳ */
        post: operations["open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/periods/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bắt đầu thu (quản trị): Đã mở → Đang thu */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/area-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Phân công đang hiệu lực vào ngày (mặc định hôm nay); công ty chỉ thấy khu vực của mình */
        get: operations["active"];
        put?: never;
        /** Phân công một hoặc nhiều khu vực cho công ty (cán bộ xã); tự đóng phân công cũ */
        post: operations["assign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thông tin tài khoản đang đăng nhập */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/tariffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Các phiên bản biểu giá kèm đơn giá theo nhóm, mới nhất trước */
        get: operations["tariffs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/periods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết kỳ thu */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/fee-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách loại phí */
        get: operations["feeTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách địa bàn */
        get: operations["districts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách công ty (công ty chỉ thấy công ty của mình) */
        get: operations["companies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết công ty (công ty khác trả 404) */
        get: operations["company"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách khu vực / tổ dân phố, lọc theo địa bàn nếu có */
        get: operations["areas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/areas/{areaId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lịch sử phân công của một khu vực, mới nhất trước (cán bộ xã, quản trị) */
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            accessToken: string;
            /** @example Bearer */
            tokenType: string;
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["MeResponse"];
        };
        MeResponse: {
            /** Format: int64 */
            id: number;
            username: string;
            fullName: string;
            /** @enum {string} */
            role: "COMMUNE_OFFICER" | "COMPANY_MANAGER" | "COLLECTOR" | "ADMIN";
            /**
             * Format: int64
             * @description Chỉ có với COMPANY_MANAGER, COLLECTOR
             */
            companyId: number | null;
        };
        OpenPeriodRequest: {
            /** @enum {string} */
            type: "MONTH" | "QUARTER";
            /**
             * Format: int32
             * @example 2026
             */
            year: number;
            /**
             * Format: int32
             * @description Tháng 1–12 hoặc quý 1–4
             * @example 10
             */
            number: number;
            /**
             * Format: date
             * @description Để trống thì lấy ngày đầu kỳ
             */
            openDate?: string;
            /**
             * Format: date
             * @description Hạn công ty nộp xã
             */
            dueDate: string;
            note?: string;
        };
        PeriodDto: {
            /** Format: int64 */
            id: number;
            /** @example 2026-10 */
            code: string;
            /** @enum {string} */
            periodType: "MONTH" | "QUARTER";
            /** @example Tháng 10/2026 */
            label: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** Format: date */
            openDate: string;
            /** Format: date */
            dueDate: string;
            /** Format: int64 */
            tariffVersionId: number;
            /** @example BG-65-2026 */
            tariffVersionCode: string;
            /** @enum {string} */
            status: "OPEN" | "COLLECTING" | "LOCKED";
            /** Format: date-time */
            lockedAt: string | null;
            note: string | null;
        };
        AssignRequest: {
            areaIds: number[];
            /** Format: int64 */
            companyId: number;
            /** Format: date */
            fromDate: string;
            note?: string;
            decisionNo?: string;
        };
        AreaAssignmentDto: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            areaId: number;
            /** @example KV07 */
            areaCode: string;
            areaName: string;
            /** Format: int64 */
            companyId: number;
            /** @example DV01 */
            companyCode: string;
            companyName: string;
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validTo: string | null;
            note: string | null;
            decisionNo: string | null;
        };
        TariffRateDto: {
            /** @enum {string} */
            tariffGroup: "HH_UP_TO_2" | "HH_3_PLUS" | "SMALL_GENERATOR" | "BY_VOLUME";
            /** Format: int64 */
            collectionFee: number;
            /** Format: int64 */
            processingFee: number;
            /** Format: int64 */
            monthlyTotal: number;
            /** @example đ/hộ/tháng */
            unitLabel: string;
        };
        TariffVersionDto: {
            /** Format: int64 */
            id: number;
            /** @example BG-65-2026 */
            code: string;
            legalBasis: string;
            /** Format: date */
            issuedDate: string | null;
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validTo: string | null;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "EXPIRED";
            scopeNote: string | null;
            note: string | null;
            rates: components["schemas"]["TariffRateDto"][];
        };
        FeeTypeDto: {
            /** Format: int64 */
            id: number;
            /** @example ENV */
            code: string;
            name: string;
            /** @enum {string} */
            pricingMode: "TARIFF" | "FIXED";
            /** Format: int64 */
            defaultPrice: number | null;
            active: boolean;
        };
        DistrictDto: {
            /** Format: int64 */
            id: number;
            /** @example DTH */
            code: string;
            name: string;
            note: string | null;
            /** Format: int32 */
            sortOrder: number | null;
        };
        CompanyDto: {
            /** Format: int64 */
            id: number;
            /** @example DV01 */
            code: string;
            name: string;
            contactName: string;
            contactPhone: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validTo: string | null;
            /** @enum {string|null} */
            orgType: "COMPANY" | "COOPERATIVE" | "PUBLIC_UNIT" | null;
            taxCode: string | null;
            address: string | null;
            email: string | null;
            communeContractNo: string | null;
            bankAccount: string | null;
            bankName: string | null;
        };
        AreaDto: {
            /** Format: int64 */
            id: number;
            /** @example KV07 */
            code: string;
            name: string;
            /** Format: int64 */
            districtId: number;
            /** @example DTH */
            districtCode: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PeriodDto"][];
                };
            };
        };
    };
    open: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenPeriodRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PeriodDto"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PeriodDto"];
                };
            };
        };
    };
    active: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AreaAssignmentDto"][];
                };
            };
        };
    };
    assign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AreaAssignmentDto"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    tariffs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TariffVersionDto"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PeriodDto"];
                };
            };
        };
    };
    feeTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeeTypeDto"][];
                };
            };
        };
    };
    districts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DistrictDto"][];
                };
            };
        };
    };
    companies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompanyDto"][];
                };
            };
        };
    };
    company: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompanyDto"];
                };
            };
        };
    };
    areas: {
        parameters: {
            query?: {
                districtId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AreaDto"][];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                areaId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AreaAssignmentDto"][];
                };
            };
        };
    };
}
