/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/masterdata/subjects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết hồ sơ hộ */
        get: operations["get"];
        /** Sửa thông tin đối tượng (cán bộ xã); hợp đồng sửa qua /contracts/{id} */
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/contracts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Sửa hợp đồng: nhóm giá, hiệu lực, miễn 100% */
        put: operations["updateContract"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remittance/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lịch sử nhắc nộp; công ty chỉ thấy của mình; settled = đã hết nợ các kỳ được nhắc */
        get: operations["list"];
        put?: never;
        /** Gửi nhắc nộp (cán bộ xã); công ty không có nợ quá hạn → 422 */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remittance/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Phiếu thu theo kỳ/công ty, kèm lũy kế đã nộp tới từng phiếu; công ty chỉ thấy phiếu của mình */
        get: operations["list_1"];
        put?: never;
        /** Lập phiếu thu khi công ty nộp tiền (cán bộ xã); số tiền ≤ còn phải nộp của kỳ */
        post: operations["issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remittance/receipt-issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sai sót phiếu thu; công ty chỉ thấy sai sót trên phiếu của mình */
        get: operations["list_2"];
        put?: never;
        /** Công ty báo sai sót trên phiếu thu của mình; thông báo tới cán bộ xã */
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remittance/receipt-issues/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Xã đánh dấu đã xử lý kèm ghi chú kết quả (không sửa phiếu, G6); thông báo về công ty */
        post: operations["resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remittance/periods/{id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Khóa kỳ (cán bộ xã); còn công ty chưa nộp đủ thì 422 kèm danh sách công ty và số nợ */
        post: operations["lock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập bằng tên đăng nhập và mật khẩu, nhận access token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đánh dấu đã đọc (chung cho cả nhóm nhận, D7) */
        post: operations["read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đánh dấu tất cả đã đọc */
        post: operations["readAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tìm hồ sơ hộ (mã, tên, SĐT, địa chỉ); công ty chỉ thấy hộ thuộc khu vực của mình */
        get: operations["search"];
        put?: never;
        /** Tạo hồ sơ hộ, kèm hợp đồng đầu tiên nếu có (cán bộ xã) */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/subjects/{id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ngừng cung cấp dịch vụ: đối tượng Đã chấm dứt, hợp đồng đang hiệu lực kết thúc */
        post: operations["end"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/subjects/{id}/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Thêm hợp đồng cho đối tượng (không được chồng hiệu lực với hợp đồng khác) */
        post: operations["addContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách kỳ thu, mới nhất trước; có date thì chỉ các kỳ chứa ngày đó */
        get: operations["list_3"];
        put?: never;
        /** Mở kỳ thu tháng/quý (quản trị); gắn biểu giá có hiệu lực tại ngày đầu kỳ */
        post: operations["open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/periods/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bắt đầu thu (quản trị): Đã mở → Đang thu */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/area-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Phân công đang hiệu lực vào ngày (mặc định hôm nay); công ty chỉ thấy khu vực của mình */
        get: operations["active"];
        put?: never;
        /** Phân công một hoặc nhiều khu vực cho công ty (cán bộ xã); tự đóng phân công cũ */
        post: operations["assign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách khiếu nại, mới nhất trước; công ty chỉ thấy khiếu nại đã chuyển cho mình (G12) */
        get: operations["list_4"];
        put?: never;
        /** Cán bộ xã ghi nhận khiếu nại qua điện thoại / trực tiếp */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints/{id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Công ty được chuyển phản hồi kết quả xử lý */
        post: operations["reply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints/{id}/forward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chuyển công ty xử lý (để trống công ty: công ty phụ trách khu vực), hạn hôm nay + 3 ngày */
        post: operations["forward"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cán bộ xã đóng khiếu nại kèm kết quả cuối */
        post: operations["close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ghi lượt ghé không thu được (vắng / hẹn / từ chối); không đổi trạng thái khoản */
        post: operations["visit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ghi nhận thanh toán (tiền mặt / chuyển khoản); gửi lại cùng clientRequestId trả kết quả cũ (200) */
        post: operations["pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/collector-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Phân tổ đang hiệu lực vào ngày (mặc định hôm nay), theo phạm vi người gọi */
        get: operations["assignments"];
        put?: never;
        /** Phân tổ cho người đi thu (quản lý công ty); người cũ của tổ kết thúc vào ngày trước */
        post: operations["assign_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/collector-assignments/{id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kết thúc phân tổ vào ngày endDate (quản lý công ty) */
        post: operations["end_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/cash/handovers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lịch sử bàn giao: người đi thu xem của mình, quản lý công ty xem của công ty */
        get: operations["handovers"];
        put?: never;
        /** Ghi nhận tiền mặt nhận từ người đi thu (quản lý công ty, G5) */
        post: operations["handover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/charge-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Phiếu yêu cầu thu đã phát hành, kèm số khoản và tổng tiền (cán bộ xã, quản trị) */
        get: operations["requests"];
        put?: never;
        /** Phát hành phiếu yêu cầu thu; 201 khi có khoản mới, 200 khi không có khoản mới (không lưu phiếu) */
        post: operations["publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/charge-requests/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Xem trước phiếu yêu cầu thu: số khoản, tổng tiền, danh sách bỏ qua (không ghi CSDL) */
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remittance/reminders/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bản nháp nhắc nộp: các kỳ quá hạn còn nợ, tổng tiền, hạn mới (+5 ngày), nội dung soạn sẵn */
        get: operations["draft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remittance/receipts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Một phiếu thu (để in: số tiền bằng chữ, lũy kế, còn phải nộp) */
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remittance/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sổ công ty–kỳ: phải thu, đã thu, đã nộp, còn nộp, nợ kỳ trước, tiến độ, đối soát. Xã và quản trị thấy mọi công ty; công ty chỉ thấy dòng của mình */
        get: operations["ledger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remittance/area-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiến độ thu theo tổ trong kỳ (công ty theo khoản đã phát hành; tổ chưa có công ty đánh dấu). Công ty chỉ thấy tổ của mình */
        get: operations["areaProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thông tin tài khoản đang đăng nhập */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thông báo của người đang đăng nhập (theo vai trò, công ty, cá nhân), mới nhất trước */
        get: operations["list_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Số thông báo chưa đọc */
        get: operations["unreadCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/tariffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Các phiên bản biểu giá kèm đơn giá theo nhóm, mới nhất trước */
        get: operations["tariffs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/periods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết kỳ thu */
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/fee-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách loại phí */
        get: operations["feeTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách địa bàn */
        get: operations["districts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách công ty (công ty chỉ thấy công ty của mình) */
        get: operations["companies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết công ty (công ty khác trả 404) */
        get: operations["company"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách khu vực / tổ dân phố, lọc theo địa bàn nếu có */
        get: operations["areas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/areas/{areaId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lịch sử phân công của một khu vực, mới nhất trước (cán bộ xã, quản trị) */
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết khiếu nại kèm timeline */
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/my-work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách thu của người đi thu: khoản trong tổ được giao, kèm đã thu và lượt ghé mới nhất */
        get: operations["myWork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/my-charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Khoản của hộ trong các tổ được giao (người đi thu) */
        get: operations["myCharges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/my-charges/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Một khoản trong phạm vi người đi thu; ngoài tổ được giao → 404 */
        get: operations["myCharge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/company-work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hộ được giao của công ty: khoản các tổ công ty phụ trách, kèm đã thu và lượt ghé mới nhất */
        get: operations["companyWork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/collectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Người đi thu của công ty (quản lý công ty) */
        get: operations["collectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/charges/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lịch sử thu của một khoản: thanh toán và lượt ghé */
        get: operations["activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection/cash/held": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiền mặt đang giữ. Người đi thu: của mình; quản lý công ty: một người (collectorId) hoặc cả công ty */
        get: operations["held"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Khoản phải thu; công ty chỉ thấy khoản của công ty mình */
        get: operations["charges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContractRequest: {
            /** @enum {string} */
            tariffGroup: "HH_UP_TO_2" | "HH_3_PLUS" | "SMALL_GENERATOR" | "BY_VOLUME";
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validTo?: string;
            exempt?: boolean;
            exemptReason?: string;
            exemptDecisionNo?: string;
            note?: string;
        };
        SubjectRequest: {
            /** @enum {string} */
            type: "HOUSEHOLD" | "BUSINESS_HOUSEHOLD" | "ENTERPRISE";
            name: string;
            address: string;
            /** Format: int64 */
            areaId: number;
            phone?: string;
            /** Format: int32 */
            memberCount?: number;
            representativeName?: string;
            taxCode?: string;
            note?: string;
            /** @description Chỉ dùng khi tạo mới: hợp đồng đầu tiên (không bắt buộc) */
            contract?: components["schemas"]["ContractRequest"];
        };
        ContractDto: {
            /** Format: int64 */
            id: number;
            /** @example ĐK-DTH-0128 */
            contractNo: string;
            /** @enum {string} */
            tariffGroup: "HH_UP_TO_2" | "HH_3_PLUS" | "SMALL_GENERATOR" | "BY_VOLUME";
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validTo: string | null;
            exempt: boolean;
            exemptReason: string | null;
            exemptDecisionNo: string | null;
            note: string | null;
        };
        SubjectDto: {
            /** Format: int64 */
            id: number;
            /** @example DTH-H000128 */
            code: string;
            /** @enum {string} */
            subjectType: "HOUSEHOLD" | "BUSINESS_HOUSEHOLD" | "ENTERPRISE";
            name: string;
            address: string;
            /** Format: int64 */
            areaId: number;
            /** @example KV07 */
            areaCode: string;
            /** @example DTH */
            districtCode: string;
            phone: string | null;
            /** @enum {string} */
            status: "ACTIVE" | "PENDING" | "ENDED";
            /** Format: int32 */
            memberCount: number | null;
            representativeName: string | null;
            taxCode: string | null;
            note: string | null;
            currentContract: components["schemas"]["ContractDto"];
            contracts: components["schemas"]["ContractDto"][];
        };
        CreateReminderRequest: {
            /** Format: int64 */
            companyId: number;
            /** @description Trống thì nhắc mọi kỳ quá hạn còn nợ */
            periodIds?: number[];
            /**
             * Format: date
             * @description Trống thì ngày nhắc + 5
             */
            dueDate?: string;
            /** @description Trống thì dùng nội dung soạn sẵn */
            content?: string;
        };
        ReminderDto: {
            /** Format: int64 */
            id: number;
            /** @example NN-001 */
            code: string;
            /** Format: int64 */
            companyId: number;
            companyCode: string;
            /** Format: date */
            reminderDate: string;
            /** Format: date */
            dueDate: string;
            periodLabels: string[];
            /** Format: int64 */
            amount: number;
            content: string;
            /** @description Đã hết nợ các kỳ được nhắc */
            settled: boolean;
        };
        IssueReceiptRequest: {
            /** Format: int64 */
            companyId: number;
            /** Format: int64 */
            periodId: number;
            /** Format: int64 */
            amount: number;
            /** @enum {string} */
            method: "CASH" | "TRANSFER";
            /**
             * Format: date
             * @description Để trống thì lấy hôm nay
             */
            receiptDate?: string;
            /** @description Để trống thì lấy người đầu mối công ty */
            payerName?: string;
            documentRef?: string;
            note?: string;
        };
        ReceiptDto: {
            /** Format: int64 */
            id: number;
            /** @example PT-CT-1026-001 */
            code: string;
            /** Format: int64 */
            companyId: number;
            companyCode: string;
            companyName: string;
            /** Format: int64 */
            periodId: number;
            periodCode: string;
            periodLabel: string;
            /** Format: int64 */
            amount: number;
            /** @description Số tiền bằng chữ (R29) */
            amountInWords: string;
            /** @enum {string} */
            method: "CASH" | "TRANSFER";
            /** Format: date */
            receiptDate: string;
            payerName: string;
            documentRef: string | null;
            note: string | null;
            /** @enum {string} */
            status: "RECORDED";
            /**
             * Format: int64
             * @description Lũy kế đã nộp tới phiếu này (R30)
             */
            cumulativePaid: number;
            /**
             * Format: int64
             * @description Phải thu của công ty trong kỳ
             */
            periodDue: number;
            /**
             * Format: int64
             * @description Còn phải nộp sau phiếu này
             */
            remainingAfter: number;
        };
        ReportIssueRequest: {
            /** Format: int64 */
            receiptId: number;
            /** @enum {string} */
            issueType: "WRONG_AMOUNT" | "WRONG_PERIOD" | "WRONG_DOCUMENT" | "NOT_OURS";
            /**
             * Format: int64
             * @description Nên nhập khi sai số tiền
             */
            correctAmount?: number;
            description: string;
        };
        IssueDto: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            receiptId: number;
            receiptCode: string;
            /** Format: int64 */
            receiptAmount: number;
            /** Format: int64 */
            companyId: number;
            companyCode: string;
            companyName: string;
            periodLabel: string;
            /** @enum {string} */
            issueType: "WRONG_AMOUNT" | "WRONG_PERIOD" | "WRONG_DOCUMENT" | "NOT_OURS";
            /** Format: int64 */
            correctAmount: number | null;
            description: string;
            /** @enum {string} */
            status: "PENDING" | "RESOLVED";
            /** Format: date-time */
            reportedAt: string;
            /** Format: date-time */
            resolvedAt: string | null;
            resolutionNote: string | null;
        };
        ResolveIssueRequest: {
            resolutionNote: string;
        };
        PeriodDto: {
            /** Format: int64 */
            id: number;
            /** @example 2026-10 */
            code: string;
            /** @enum {string} */
            periodType: "MONTH" | "QUARTER";
            /** @example Tháng 10/2026 */
            label: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** Format: date */
            openDate: string;
            /** Format: date */
            dueDate: string;
            /** Format: int64 */
            tariffVersionId: number;
            /** @example BG-65-2026 */
            tariffVersionCode: string;
            /** @enum {string} */
            status: "OPEN" | "COLLECTING" | "LOCKED";
            /** Format: date-time */
            lockedAt: string | null;
            note: string | null;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            accessToken: string;
            /** @example Bearer */
            tokenType: string;
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["MeResponse"];
        };
        MeResponse: {
            /** Format: int64 */
            id: number;
            username: string;
            fullName: string;
            /** @enum {string} */
            role: "COMMUNE_OFFICER" | "COMPANY_MANAGER" | "COLLECTOR" | "ADMIN";
            /**
             * Format: int64
             * @description Chỉ có với COMPANY_MANAGER, COLLECTOR
             */
            companyId: number | null;
        };
        NotificationDto: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            kind: "REMINDER" | "COMPLAINT" | "RECEIPT" | "INFO" | "TRANSACTION";
            title: string;
            body: string;
            link: components["schemas"]["NotificationLink"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            readAt: string | null;
        };
        NotificationLink: {
            /** @example remittance.receipts */
            screen: string;
            /** @description Tham số màn hình, vd. {"periodId": 5} */
            params?: {
                [key: string]: unknown;
            };
        };
        UnreadCountDto: {
            /** Format: int64 */
            unreadCount: number;
        };
        EndSubjectRequest: {
            /**
             * Format: date
             * @description Ngày cuối cùng còn cung cấp dịch vụ
             */
            endDate: string;
            reason?: string;
        };
        OpenPeriodRequest: {
            /** @enum {string} */
            type: "MONTH" | "QUARTER";
            /**
             * Format: int32
             * @example 2026
             */
            year: number;
            /**
             * Format: int32
             * @description Tháng 1–12 hoặc quý 1–4
             * @example 10
             */
            number: number;
            /**
             * Format: date
             * @description Để trống thì lấy ngày đầu kỳ
             */
            openDate?: string;
            /**
             * Format: date
             * @description Hạn công ty nộp xã
             */
            dueDate: string;
            note?: string;
        };
        AssignRequest: {
            areaIds: number[];
            /** Format: int64 */
            companyId: number;
            /** Format: date */
            fromDate: string;
            note?: string;
            decisionNo?: string;
        };
        AreaAssignmentDto: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            areaId: number;
            /** @example KV07 */
            areaCode: string;
            areaName: string;
            /** Format: int64 */
            companyId: number;
            /** @example DV01 */
            companyCode: string;
            companyName: string;
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validTo: string | null;
            note: string | null;
            decisionNo: string | null;
        };
        CreateComplaintRequest: {
            complainantName: string;
            complainantPhone?: string;
            /**
             * Format: int64
             * @description Hộ / đối tượng liên quan, nếu biết
             */
            subjectId?: number;
            /**
             * Format: int64
             * @description Để trống thì lấy khu vực của hộ
             */
            areaId?: number;
            /** @enum {string} */
            channel: "APP" | "PHONE" | "IN_PERSON";
            /** @enum {string} */
            category: "LATE_COLLECTION" | "OVERCHARGE" | "POLLUTION_POINT" | "STAFF_ATTITUDE" | "OTHER";
            summary: string;
            content: string;
            /**
             * Format: date
             * @description Để trống thì lấy hôm nay
             */
            receivedDate?: string;
        };
        ComplaintDetailDto: {
            complaint: components["schemas"]["ComplaintDto"];
            events: components["schemas"]["EventDto"][];
        };
        ComplaintDto: {
            /** Format: int64 */
            id: number;
            /** @example KN-1026-001 */
            code: string;
            /** Format: date */
            receivedDate: string;
            complainantName: string;
            complainantPhone: string | null;
            /** Format: int64 */
            subjectId: number | null;
            subjectCode: string | null;
            subjectName: string | null;
            /** Format: int64 */
            areaId: number;
            areaCode: string;
            areaName: string;
            /** @enum {string} */
            channel: "APP" | "PHONE" | "IN_PERSON";
            /** @enum {string} */
            category: "LATE_COLLECTION" | "OVERCHARGE" | "POLLUTION_POINT" | "STAFF_ATTITUDE" | "OTHER";
            summary: string;
            content: string;
            /** @enum {string} */
            status: "NEW" | "PROCESSING" | "RESOLVED";
            /** Format: int64 */
            forwardedCompanyId: number | null;
            forwardedCompanyCode: string | null;
            forwardedCompanyName: string | null;
            /** Format: date */
            deadline: string | null;
            /** @description Chưa giải quyết và đã qua hạn */
            overdue: boolean;
            resolution: string | null;
            /** Format: date-time */
            resolvedAt: string | null;
        };
        EventDto: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            eventType: "SUBMITTED" | "RECEIVED" | "FORWARDED" | "COMPANY_REPLIED" | "CLOSED";
            /** Format: date-time */
            occurredAt: string;
            actorLabel: string;
            content: string;
        };
        ReplyRequest: {
            content: string;
        };
        ForwardRequest: {
            /**
             * Format: int64
             * @description Để trống thì lấy công ty phụ trách khu vực
             */
            companyId?: number;
            note?: string;
        };
        CloseRequest: {
            resolution: string;
        };
        VisitRequest: {
            /** Format: int64 */
            chargeId: number;
            /** @enum {string} */
            result: "ABSENT" | "APPOINTMENT" | "REFUSED";
            /**
             * Format: date
             * @description Bắt buộc khi hẹn lại
             */
            revisitDate?: string;
            note?: string;
            clientRequestId: string;
        };
        VisitDto: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            chargeId: number;
            /** @enum {string} */
            result: "ABSENT" | "APPOINTMENT" | "REFUSED";
            /** Format: date-time */
            visitedAt: string;
            /** Format: date */
            revisitDate: string | null;
            note: string | null;
        };
        PaymentRequest: {
            /** Format: int64 */
            chargeId: number;
            /** Format: int64 */
            amount: number;
            /** @enum {string} */
            method: "CASH" | "TRANSFER" | "APP_SIMULATED";
            /** @description UUID do client sinh, chống gửi trùng */
            clientRequestId: string;
            bankRef?: string;
            note?: string;
            /**
             * Format: int64
             * @description Bắt buộc khi quản lý công ty ghi thay: người đi thu đã nhận tiền
             */
            collectorId?: number;
        };
        PaymentDto: {
            /** Format: int64 */
            id: number;
            /** @example TT-1026-000123 */
            code: string;
            /** Format: int64 */
            amount: number;
            /** @enum {string} */
            method: "CASH" | "TRANSFER" | "APP_SIMULATED";
            /** Format: date-time */
            paidAt: string;
            /** Format: int64 */
            collectorId: number | null;
            note: string | null;
        };
        PaymentResultDto: {
            payment: components["schemas"]["PaymentDto"];
            chargeCode: string;
            /** @enum {string} */
            chargeStatus: "UNPAID" | "PAID" | "EXEMPT";
            /** Format: int64 */
            paidAmount: number;
            /** Format: int64 */
            remainingAmount: number;
            /** @description true khi gửi lại cùng clientRequestId */
            replayed: boolean;
        };
        AssignCollectorRequest: {
            /** Format: int64 */
            collectorId: number;
            areaIds: number[];
            /** Format: date */
            fromDate: string;
            note?: string;
        };
        CollectorAssignmentDto: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            collectorId: number;
            collectorUsername: string;
            collectorName: string;
            /** Format: int64 */
            areaId: number;
            areaCode: string;
            areaName: string;
            /** Format: int64 */
            companyId: number;
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validTo: string | null;
            note: string | null;
        };
        EndAssignmentRequest: {
            /** Format: date */
            endDate: string;
        };
        HandoverRequest: {
            /** Format: int64 */
            collectorId: number;
            /** Format: int64 */
            amount: number;
            /**
             * Format: date
             * @description Để trống thì lấy hôm nay
             */
            handoverDate?: string;
            note?: string;
        };
        HandoverDto: {
            /** Format: int64 */
            id: number;
            /** @example BG-1026-01 */
            code: string;
            /** Format: int64 */
            collectorId: number;
            collectorName: string;
            /** Format: date */
            handoverDate: string;
            /** Format: int64 */
            amount: number;
            note: string | null;
        };
        IssueRequest: {
            /** Format: int64 */
            periodId: number;
            /** Format: int64 */
            feeTypeId: number;
            /** @enum {string} */
            scopeType: "ALL" | "AREAS" | "COMPANY";
            /** @description Bắt buộc khi scopeType = AREAS */
            areaIds?: number[];
            /**
             * Format: int64
             * @description Bắt buộc khi scopeType = COMPANY
             */
            companyId?: number;
            /**
             * Format: date
             * @description Hạn hộ đóng, không sau hạn công ty nộp xã
             */
            dueDate: string;
            /**
             * Format: int64
             * @description Chỉ với loại phí giá cố định; trống thì dùng giá mặc định
             */
            unitPrice?: number;
            note?: string;
        };
        IssueResultDto: {
            /** @description Null khi không có khoản mới */
            requestCode: string | null;
            /** Format: int32 */
            chargeCount: number;
            /** Format: int32 */
            exemptCount: number;
            /** Format: int64 */
            totalAmount: number;
            /** Format: int32 */
            warningCount: number;
            skipped: components["schemas"]["SkippedDto"][];
        };
        SkippedDto: {
            /** Format: int64 */
            subjectId: number;
            subjectCode: string;
            subjectName: string;
            areaCode: string;
            /** @enum {string} */
            reason: "SUBJECT_NOT_ACTIVE" | "NO_ACTIVE_CONTRACT" | "AREA_WITHOUT_COMPANY" | "DUPLICATE_CHARGE";
            warning: boolean;
            message: string;
        };
        DebtDto: {
            /** Format: int64 */
            periodId: number;
            periodLabel: string;
            /** Format: date */
            periodDueDate: string;
            /** Format: int64 */
            remaining: number;
        };
        DraftDto: {
            /** Format: int64 */
            companyId: number;
            companyCode: string;
            companyName: string;
            debts: components["schemas"]["DebtDto"][];
            /** Format: int64 */
            amount: number;
            /** Format: date */
            dueDate: string;
            content: string;
        };
        LedgerRowDto: {
            /** Format: int64 */
            companyId: number;
            companyCode: string;
            companyName: string;
            /** Format: int64 */
            periodId: number;
            /**
             * Format: int64
             * @description Phải thu
             */
            due: number;
            /** Format: int64 */
            chargeCount: number;
            /**
             * Format: int64
             * @description Công ty đã thu của hộ
             */
            collected: number;
            /**
             * Format: int64
             * @description Đã nộp về xã
             */
            received: number;
            /** Format: int64 */
            receiptCount: number;
            /**
             * Format: int64
             * @description Còn phải nộp
             */
            remaining: number;
            /**
             * Format: int64
             * @description Đã nộp − đã thu; âm là thu rồi chưa nộp
             */
            gap: number;
            /**
             * Format: int64
             * @description Nợ các kỳ trước đã hết hạn
             */
            previousDebt: number;
            overdue: boolean;
            /**
             * Format: double
             * @description Đã thu / phải thu (%)
             */
            collectionRate: number;
            /** @description Tỷ lệ thu dưới 45% */
            lowCollectionRate: boolean;
            /** @enum {string} */
            progress: "NO_COMPANY" | "PAID_IN_FULL" | "OVERDUE" | "PARTIAL" | "NOT_PAID";
            /** @enum {string} */
            reconciliation: "MATCHED" | "PENDING" | "MISMATCH";
        };
        AreaProgressDto: {
            /** Format: int64 */
            areaId: number;
            areaCode: string;
            areaName: string;
            districtCode: string;
            /** Format: int64 */
            companyId: number | null;
            companyCode: string | null;
            /** Format: int64 */
            due: number;
            /** Format: int64 */
            collected: number;
            /** Format: int64 */
            chargeCount: number;
            /** Format: int64 */
            paidCount: number;
            /** Format: int64 */
            subjectCount: number;
            /** Format: double */
            collectionRate: number;
            lowCollectionRate: boolean;
            /** @description Tổ chưa có công ty (R13) */
            noCompany: boolean;
        };
        NotificationPageDto: {
            items: components["schemas"]["NotificationDto"][];
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            unreadCount: number;
        };
        TariffRateDto: {
            /** @enum {string} */
            tariffGroup: "HH_UP_TO_2" | "HH_3_PLUS" | "SMALL_GENERATOR" | "BY_VOLUME";
            /** Format: int64 */
            collectionFee: number;
            /** Format: int64 */
            processingFee: number;
            /** Format: int64 */
            monthlyTotal: number;
            /** @example đ/hộ/tháng */
            unitLabel: string;
        };
        TariffVersionDto: {
            /** Format: int64 */
            id: number;
            /** @example BG-65-2026 */
            code: string;
            legalBasis: string;
            /** Format: date */
            issuedDate: string | null;
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validTo: string | null;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "EXPIRED";
            scopeNote: string | null;
            note: string | null;
            rates: components["schemas"]["TariffRateDto"][];
        };
        SubjectPageDto: {
            items: components["schemas"]["SubjectDto"][];
            /** Format: int64 */
            total: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
        };
        FeeTypeDto: {
            /** Format: int64 */
            id: number;
            /** @example ENV */
            code: string;
            name: string;
            /** @enum {string} */
            pricingMode: "TARIFF" | "FIXED";
            /** Format: int64 */
            defaultPrice: number | null;
            active: boolean;
        };
        DistrictDto: {
            /** Format: int64 */
            id: number;
            /** @example DTH */
            code: string;
            name: string;
            note: string | null;
            /** Format: int32 */
            sortOrder: number | null;
        };
        CompanyDto: {
            /** Format: int64 */
            id: number;
            /** @example DV01 */
            code: string;
            name: string;
            contactName: string;
            contactPhone: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validTo: string | null;
            /** @enum {string|null} */
            orgType: "COMPANY" | "COOPERATIVE" | "PUBLIC_UNIT" | null;
            taxCode: string | null;
            address: string | null;
            email: string | null;
            communeContractNo: string | null;
            bankAccount: string | null;
            bankName: string | null;
        };
        AreaDto: {
            /** Format: int64 */
            id: number;
            /** @example KV07 */
            code: string;
            name: string;
            /** Format: int64 */
            districtId: number;
            /** @example DTH */
            districtCode: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            /**
             * Format: int64
             * @description Số đối tượng chưa chấm dứt
             */
            subjectCount: number;
        };
        ChargeDto: {
            /** Format: int64 */
            id: number;
            /** @example KT-1026-DTH-H000128 */
            code: string;
            requestCode: string;
            /** Format: int64 */
            subjectId: number;
            subjectCode: string;
            subjectName: string;
            subjectAddress: string;
            /** Format: int64 */
            areaId: number;
            areaCode: string;
            /** Format: int64 */
            companyId: number;
            companyCode: string;
            /** Format: int64 */
            periodId: number;
            periodCode: string;
            feeTypeCode: string;
            /** @enum {string|null} */
            tariffGroup: "HH_UP_TO_2" | "HH_3_PLUS" | "SMALL_GENERATOR" | "BY_VOLUME" | null;
            /** Format: int64 */
            unitPrice: number;
            /** Format: int32 */
            months: number;
            /** Format: int64 */
            amount: number;
            /** Format: date */
            dueDate: string;
            /** @enum {string} */
            status: "UNPAID" | "PAID" | "EXEMPT";
            /** @description Chưa thu và đã qua hạn đóng */
            overdue: boolean;
        };
        CollectorChargeDto: {
            charge: components["schemas"]["ChargeDto"];
            /** Format: int64 */
            paidAmount: number;
            /** Format: int64 */
            remainingAmount: number;
            lastVisit: components["schemas"]["VisitDto"];
        };
        ChargePageDto: {
            items: components["schemas"]["ChargeDto"][];
            /** Format: int64 */
            total: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
        };
        CollectorDto: {
            /** Format: int64 */
            id: number;
            username: string;
            fullName: string;
            phone: string | null;
            active: boolean;
        };
        ActivityDto: {
            charge: components["schemas"]["ChargeDto"];
            /** Format: int64 */
            paidAmount: number;
            /** Format: int64 */
            remainingAmount: number;
            payments: components["schemas"]["PaymentDto"][];
            visits: components["schemas"]["VisitDto"][];
        };
        CashHeldDto: {
            /** Format: int64 */
            collectorId: number;
            collectorUsername: string;
            collectorName: string;
            /**
             * Format: int64
             * @description Tiền mặt đã thu (mọi kỳ)
             */
            collectedCash: number;
            /** Format: int64 */
            handedOver: number;
            /**
             * Format: int64
             * @description Đang giữ
             */
            held: number;
        };
        ChargeRequestDto: {
            /** Format: int64 */
            id: number;
            /** @example YCT-1026-01 */
            code: string;
            /** Format: int64 */
            periodId: number;
            periodCode: string;
            feeTypeCode: string;
            feeTypeName: string;
            /** @enum {string} */
            scopeType: "ALL" | "AREAS" | "COMPANY";
            /** Format: date */
            issueDate: string;
            /** Format: date */
            dueDate: string;
            /** Format: int64 */
            unitPrice: number | null;
            /** Format: int64 */
            chargeCount: number;
            /** Format: int64 */
            exemptCount: number;
            /** Format: int64 */
            totalAmount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubjectDto"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubjectDto"];
                };
            };
        };
    };
    updateContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContractDto"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                companyId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReminderDto"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReminderRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReminderDto"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                periodId?: number;
                companyId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReceiptDto"][];
                };
            };
        };
    };
    issue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueReceiptRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReceiptDto"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                status?: "PENDING" | "RESOLVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssueDto"][];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportIssueRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssueDto"];
                };
            };
        };
    };
    resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveIssueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssueDto"];
                };
            };
        };
    };
    lock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PeriodDto"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationDto"];
                };
            };
        };
    };
    readAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UnreadCountDto"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                districtId?: number;
                areaId?: number;
                status?: "ACTIVE" | "PENDING" | "ENDED";
                q?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubjectPageDto"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubjectDto"];
                };
            };
        };
    };
    end: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EndSubjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubjectDto"];
                };
            };
        };
    };
    addContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContractDto"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PeriodDto"][];
                };
            };
        };
    };
    open: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenPeriodRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PeriodDto"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PeriodDto"];
                };
            };
        };
    };
    active: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AreaAssignmentDto"][];
                };
            };
        };
    };
    assign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AreaAssignmentDto"][];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: {
                status?: "NEW" | "PROCESSING" | "RESOLVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ComplaintDto"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateComplaintRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ComplaintDetailDto"];
                };
            };
        };
    };
    reply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ComplaintDetailDto"];
                };
            };
        };
    };
    forward: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForwardRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ComplaintDetailDto"];
                };
            };
        };
    };
    close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ComplaintDetailDto"];
                };
            };
        };
    };
    visit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VisitDto"];
                };
            };
        };
    };
    pay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaymentResultDto"];
                };
            };
        };
    };
    assignments: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectorAssignmentDto"][];
                };
            };
        };
    };
    assign_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignCollectorRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectorAssignmentDto"][];
                };
            };
        };
    };
    end_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EndAssignmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectorAssignmentDto"];
                };
            };
        };
    };
    handovers: {
        parameters: {
            query?: {
                collectorId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HandoverDto"][];
                };
            };
        };
    };
    handover: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoverRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HandoverDto"];
                };
            };
        };
    };
    requests: {
        parameters: {
            query?: {
                periodId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChargeRequestDto"][];
                };
            };
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssueResultDto"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssueResultDto"];
                };
            };
        };
    };
    draft: {
        parameters: {
            query: {
                companyId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DraftDto"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReceiptDto"];
                };
            };
        };
    };
    ledger: {
        parameters: {
            query: {
                periodId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LedgerRowDto"][];
                };
            };
        };
    };
    areaProgress: {
        parameters: {
            query: {
                periodId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AreaProgressDto"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: {
                unreadOnly?: boolean;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationPageDto"];
                };
            };
        };
    };
    unreadCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UnreadCountDto"];
                };
            };
        };
    };
    tariffs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TariffVersionDto"][];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PeriodDto"];
                };
            };
        };
    };
    feeTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeeTypeDto"][];
                };
            };
        };
    };
    districts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DistrictDto"][];
                };
            };
        };
    };
    companies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompanyDto"][];
                };
            };
        };
    };
    company: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompanyDto"];
                };
            };
        };
    };
    areas: {
        parameters: {
            query?: {
                districtId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AreaDto"][];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                areaId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AreaAssignmentDto"][];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ComplaintDetailDto"];
                };
            };
        };
    };
    myWork: {
        parameters: {
            query?: {
                periodId?: number;
                status?: "UNPAID" | "PAID" | "EXEMPT";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectorChargeDto"][];
                };
            };
        };
    };
    myCharges: {
        parameters: {
            query?: {
                periodId?: number;
                status?: "UNPAID" | "PAID" | "EXEMPT";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChargePageDto"];
                };
            };
        };
    };
    myCharge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChargeDto"];
                };
            };
        };
    };
    companyWork: {
        parameters: {
            query?: {
                periodId?: number;
                areaId?: number;
                status?: "UNPAID" | "PAID" | "EXEMPT";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectorChargeDto"][];
                };
            };
        };
    };
    collectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectorDto"][];
                };
            };
        };
    };
    activity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityDto"];
                };
            };
        };
    };
    held: {
        parameters: {
            query?: {
                collectorId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CashHeldDto"][];
                };
            };
        };
    };
    charges: {
        parameters: {
            query?: {
                periodId?: number;
                areaId?: number;
                status?: "UNPAID" | "PAID" | "EXEMPT";
                subjectId?: number;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChargePageDto"];
                };
            };
        };
    };
}
