/** Nhãn mã hành động backend ghi vào nhật ký; mã mới chưa có ở đây thì màn nhật ký hiện nguyên mã. */
export const AUDIT_ACTION_LABELS: Record<string, string> = {
  CREATE_USER: 'Tạo tài khoản',
  UPDATE_USER: 'Sửa tài khoản',
  LOCK_USER: 'Khóa tài khoản',
  UNLOCK_USER: 'Mở khóa tài khoản',
  RESET_PASSWORD: 'Đặt lại mật khẩu',
  CREATE_COMPANY: 'Thêm công ty',
  UPDATE_COMPANY: 'Sửa thông tin công ty',
  UPDATE_DISTRICT: 'Sửa địa bàn',
  UPDATE_AREA: 'Sửa khu vực',
  UPDATE_TARIFF_VERSION: 'Sửa biểu giá đã ban hành',
  CREATE_TARIFF_DRAFT: 'Tạo biểu giá nháp',
  UPDATE_TARIFF_DRAFT: 'Sửa biểu giá nháp',
  ISSUE_TARIFF_VERSION: 'Ban hành biểu giá',
  END_TARIFF_VERSION: 'Kết thúc biểu giá',
  ASSIGN_AREA: 'Phân công khu vực cho công ty',
  ASSIGN_COLLECTOR: 'Phân tổ cho người đi thu',
  END_COLLECTOR_ASSIGNMENT: 'Kết thúc phân tổ',
  CREATE_SUBJECT: 'Thêm đối tượng',
  UPDATE_SUBJECT: 'Sửa đối tượng',
  END_SUBJECT: 'Ngừng cung cấp dịch vụ',
  CREATE_CONTRACT: 'Đăng ký dịch vụ',
  UPDATE_CONTRACT: 'Sửa đăng ký dịch vụ',
  OPEN_PERIOD: 'Mở kỳ thu',
  CREATE_DRAFT_PERIOD: 'Hệ thống tự tạo kỳ thu dự thảo',
  PUBLISH_PERIOD: 'Mở kỳ thu và phát hành',
  UPDATE_PERIOD_RULE: 'Sửa quy tắc tự tạo kỳ thu',
  LOCK_PERIOD: 'Khóa kỳ thu',
  ISSUE_CHARGE_REQUEST: 'Phát hành phiếu yêu cầu thu',
  RECORD_PAYMENT: 'Ghi nhận thanh toán',
  RECORD_CITIZEN_PAYMENT: 'Người dân thanh toán trên app',
  RECORD_BANK_TRANSFER: 'Ngân hàng báo chuyển khoản (SePay)',
  RECEIVE_CASH_HANDOVER: 'Nhận bàn giao tiền mặt',
  ISSUE_COMPANY_RECEIPT: 'Lập phiếu thu cho công ty',
  REPORT_RECEIPT_ISSUE: 'Báo sai sót phiếu thu',
  RESOLVE_RECEIPT_ISSUE: 'Xử lý sai sót phiếu thu',
  CREATE_PAYMENT_REMINDER: 'Gửi nhắc nộp',
  REPORT_SUBJECT: 'Báo sai thông tin hộ',
  CREATE_APPROVAL: 'Lập đề nghị miễn giảm / hoàn / xóa nợ',
  APPROVE_APPROVAL: 'Duyệt đề nghị',
  REJECT_APPROVAL: 'Từ chối đề nghị',
  CREATE_BULKY: 'Người dân đăng ký rác cồng kềnh',
  CITIZEN_CANCEL_BULKY: 'Người dân hủy yêu cầu rác cồng kềnh',
  QUOTE_BULKY_FEE: 'Báo phí rác cồng kềnh',
  COLLECT_BULKY: 'Thu gom rác cồng kềnh',
  CANCEL_BULKY: 'Từ chối yêu cầu rác cồng kềnh',
};

/** Tên đối tượng theo tiêu đề entity trong data dictionary. */
export const AUDIT_ENTITY_LABELS: Record<string, string> = {
  User: 'Tài khoản',
  Company: 'Công ty môi trường',
  District: 'Địa bàn',
  Area: 'Khu vực',
  TariffVersion: 'Biểu giá',
  AreaAssignment: 'Phân công khu vực cho công ty',
  CollectorAssignment: 'Phân tổ cho người đi thu',
  ServiceSubject: 'Đối tượng sử dụng dịch vụ',
  ServiceContract: 'Đăng ký dịch vụ',
  CollectionPeriod: 'Kỳ thu',
  PeriodAutoRule: 'Quy tắc tự tạo kỳ thu',
  ChargeRequest: 'Phiếu yêu cầu thu',
  Charge: 'Khoản phải thu của hộ',
  CashHandover: 'Bàn giao tiền mặt',
  CompanyReceipt: 'Phiếu thu xã lập cho công ty',
  ReceiptIssue: 'Báo sai sót phiếu thu',
  ApprovalRequest: 'Đề nghị miễn giảm / hoàn / xóa nợ',
  PaymentReminder: 'Nhắc nộp',
  BulkyWasteRequest: 'Đăng ký thu gom rác cồng kềnh',
};
