-- Seed demo (chỉ profile demo): danh mục đường/hẻm xã Đông Thạnh, sinh bởi scripts/osm_duong_dong_thanh.py
-- từ bản nháp docs/dia-chi/danh-sach-duong-dong-thanh-nhap.xlsx, GIẢ ĐỊNH xã đã duyệt: đổi tên 18 tuyến theo
-- NQ 380/NQ-HĐND ngày 24/7/2025 (giữ tên cũ), bỏ cầu, đường phường bên cạnh, hẻm không rõ đường cha.
-- Nguồn: © OpenStreetMap contributors (ODbL). Khi có danh mục chính thức, quản trị viên nhập lại bằng Excel.
-- "on conflict do nothing": DB demo cũ có thể đã có đường cùng tên (thêm tay trước V49).

insert into streets (kind, name, name_key) values
    ('STREET', 'Bùi Công Trừng', 'bui cong trung'),
    ('STREET', 'Bùi Thị Lùng', 'bui thi lung'),
    ('STREET', 'Bùi Văn Ngữ', 'bui van ngu'),
    ('STREET', 'Bờ Bao Rạch Bến Đá', 'bo bao rach ben da'),
    ('STREET', 'Huỳnh Thị Hai', 'huynh thi hai'),
    ('STREET', 'Huỳnh Thị Na', 'huynh thi na'),
    ('STREET', 'Huỳnh Thị Xe', 'huynh thi xe'),
    ('STREET', 'Kênh Trần Quang Cơ', 'kenh tran quang co'),
    ('STREET', 'Lê Thị Thìn', 'le thi thin'),
    ('STREET', 'Lê Văn Khương', 'le van khuong'),
    ('STREET', 'Nguyễn Thị Be', 'nguyen thi be'),
    ('STREET', 'Nguyễn Thị Búp', 'nguyen thi bup'),
    ('STREET', 'Nguyễn Thị Chồn', 'nguyen thi chon'),
    ('STREET', 'Nguyễn Thị Dễ', 'nguyen thi de'),
    ('STREET', 'Nguyễn Thị Mực', 'nguyen thi muc'),
    ('STREET', 'Nguyễn Thị Nghé', 'nguyen thi nghe'),
    ('STREET', 'Nguyễn Thị Ngâu', 'nguyen thi ngau'),
    ('STREET', 'Nguyễn Thị Pha', 'nguyen thi pha'),
    ('STREET', 'Nguyễn Thị Sáng', 'nguyen thi sang'),
    ('STREET', 'Nguyễn Thị Sáu', 'nguyen thi sau'),
    ('STREET', 'Nguyễn Thị Thảnh', 'nguyen thi thanh'),
    ('STREET', 'Nguyễn Thị Tạo', 'nguyen thi tao'),
    ('STREET', 'Nguyễn Thị Út', 'nguyen thi ut'),
    ('STREET', 'Nguyễn Thị Điệp', 'nguyen thi diep'),
    ('STREET', 'Nguyễn Thị Đẹt', 'nguyen thi det'),
    ('STREET', 'Nguyễn Ảnh Thủ', 'nguyen anh thu'),
    ('STREET', 'Nhánh Sáu Đô', 'nhanh sau do'),
    ('STREET', 'Nhị Bình 10A', 'nhi binh 10a'),
    ('STREET', 'Nhị Bình 12', 'nhi binh 12'),
    ('STREET', 'Nhị Bình 14', 'nhi binh 14'),
    ('STREET', 'Nhị Bình 15A', 'nhi binh 15a'),
    ('STREET', 'Nhị Bình 16', 'nhi binh 16'),
    ('STREET', 'Nhị Bình 17', 'nhi binh 17'),
    ('STREET', 'Nhị Bình 19', 'nhi binh 19'),
    ('STREET', 'Nhị Bình 2', 'nhi binh 2'),
    ('STREET', 'Nhị Bình 20A', 'nhi binh 20a'),
    ('STREET', 'Nhị Bình 21', 'nhi binh 21'),
    ('STREET', 'Nhị Bình 22', 'nhi binh 22'),
    ('STREET', 'Nhị Bình 26', 'nhi binh 26'),
    ('STREET', 'Nhị Bình 4', 'nhi binh 4'),
    ('STREET', 'Nhị Bình 5', 'nhi binh 5'),
    ('STREET', 'Nhị Bình 7', 'nhi binh 7'),
    ('STREET', 'Nhị Bình 8', 'nhi binh 8'),
    ('STREET', 'Nhị Bình 9', 'nhi binh 9'),
    ('STREET', 'Phùng Thị Chuyện', 'phung thi chuyen'),
    ('STREET', 'Phạm Thị Giây', 'pham thi giay'),
    ('STREET', 'Phạm Thị Tôm', 'pham thi tom'),
    ('STREET', 'Quang Trung', 'quang trung'),
    ('STREET', 'Rạch Cầu Cụt', 'rach cau cut'),
    ('STREET', 'Rạch Hai Tập', 'rach hai tap'),
    ('STREET', 'Rạch Nhum', 'rach nhum'),
    ('STREET', 'Rạch Tư Hía', 'rach tu hia'),
    ('STREET', 'Sỏi Đỏ', 'soi do'),
    ('STREET', 'Tam Đông 1', 'tam dong 1'),
    ('STREET', 'Tam Đông 11', 'tam dong 11'),
    ('STREET', 'Tam Đông 12', 'tam dong 12'),
    ('STREET', 'Tam Đông 19', 'tam dong 19'),
    ('STREET', 'Tam Đông 20', 'tam dong 20'),
    ('STREET', 'Tam Đông 22', 'tam dong 22'),
    ('STREET', 'Tam Đông 25', 'tam dong 25'),
    ('STREET', 'Tam Đông 26', 'tam dong 26'),
    ('STREET', 'Thái Thị Mén', 'thai thi men'),
    ('STREET', 'Thới Tam Thôn 10', 'thoi tam thon 10'),
    ('STREET', 'Thới Tam Thôn 11A', 'thoi tam thon 11a'),
    ('STREET', 'Thới Tam Thôn 11B', 'thoi tam thon 11b'),
    ('STREET', 'Thới Tam Thôn 11C', 'thoi tam thon 11c'),
    ('STREET', 'Thới Tam Thôn 12BIS', 'thoi tam thon 12bis'),
    ('STREET', 'Thới Tam Thôn 13', 'thoi tam thon 13'),
    ('STREET', 'Thới Tam Thôn 14', 'thoi tam thon 14'),
    ('STREET', 'Thới Tam Thôn 15', 'thoi tam thon 15'),
    ('STREET', 'Thới Tam Thôn 16', 'thoi tam thon 16'),
    ('STREET', 'Thới Tam Thôn 17', 'thoi tam thon 17'),
    ('STREET', 'Thới Tam Thôn 18', 'thoi tam thon 18'),
    ('STREET', 'Thới Tam Thôn 28', 'thoi tam thon 28'),
    ('STREET', 'Thới Tam Thôn 6', 'thoi tam thon 6'),
    ('STREET', 'Thới Tam Thôn 7C', 'thoi tam thon 7c'),
    ('STREET', 'Thới Tam Thôn 7J', 'thoi tam thon 7j'),
    ('STREET', 'Thới Tam Thôn Tuyến 2', 'thoi tam thon tuyen 2'),
    ('STREET', 'Thới Tứ 1', 'thoi tu 1'),
    ('STREET', 'Thới Tứ 2', 'thoi tu 2'),
    ('STREET', 'Thới Tứ 5', 'thoi tu 5'),
    ('STREET', 'Thời Tam Thôn 9', 'thoi tam thon 9'),
    ('STREET', 'Trung Đông 1', 'trung dong 1'),
    ('STREET', 'Trung Đông 10', 'trung dong 10'),
    ('STREET', 'Trung Đông 11', 'trung dong 11'),
    ('STREET', 'Trung Đông 12', 'trung dong 12'),
    ('STREET', 'Trung Đông 5', 'trung dong 5'),
    ('STREET', 'Trung Đông 6', 'trung dong 6'),
    ('STREET', 'Trung Đông 7', 'trung dong 7'),
    ('STREET', 'Trung Đông 8', 'trung dong 8'),
    ('STREET', 'Trương Thị Trưng', 'truong thi trung'),
    ('STREET', 'Trần Khắc Chân', 'tran khac chan'),
    ('STREET', 'Trần Quang Cơ', 'tran quang co'),
    ('STREET', 'Trần Thị Bốc', 'tran thi boc'),
    ('STREET', 'Trần Thị Hơn', 'tran thi hon'),
    ('STREET', 'Trần Thị Năm', 'tran thi nam'),
    ('STREET', 'Trần Văn Danh', 'tran van danh'),
    ('STREET', 'Trịnh Thị Dối', 'trinh thi doi'),
    ('STREET', 'Trịnh Thị Miếng', 'trinh thi mieng'),
    ('STREET', 'Tô Ký', 'to ky'),
    ('STREET', 'Tô Ký - Ngã Ba Tam Đông', 'to ky - nga ba tam dong'),
    ('STREET', 'Tô Ký 12', 'to ky 12'),
    ('STREET', 'Võ Thị Lùng', 'vo thi lung'),
    ('STREET', 'Võ Thị Tới', 'vo thi toi'),
    ('STREET', 'Võ Thị Đầy', 'vo thi day'),
    ('STREET', 'Đê Bao Nhị Bình 22', 'de bao nhi binh 22'),
    ('STREET', 'Đê Bao Sông Sài Gòn', 'de bao song sai gon'),
    ('STREET', 'Đông Thạnh 1-3', 'dong thanh 1-3'),
    ('STREET', 'Đông Thạnh 1-4', 'dong thanh 1-4'),
    ('STREET', 'Đông Thạnh 1-5', 'dong thanh 1-5'),
    ('STREET', 'Đông Thạnh 2-2', 'dong thanh 2-2'),
    ('STREET', 'Đông Thạnh 2-3', 'dong thanh 2-3'),
    ('STREET', 'Đông Thạnh 2-3-1', 'dong thanh 2-3-1'),
    ('STREET', 'Đông Thạnh 2-6', 'dong thanh 2-6'),
    ('STREET', 'Đông Thạnh 2-7', 'dong thanh 2-7'),
    ('STREET', 'Đông Thạnh 3-1', 'dong thanh 3-1'),
    ('STREET', 'Đông Thạnh 3-3-1', 'dong thanh 3-3-1'),
    ('STREET', 'Đông Thạnh 3-4', 'dong thanh 3-4'),
    ('STREET', 'Đông Thạnh 4-2', 'dong thanh 4-2'),
    ('STREET', 'Đông Thạnh 4-2 Nhánh 1', 'dong thanh 4-2 nhanh 1'),
    ('STREET', 'Đông Thạnh 6-4', 'dong thanh 6-4'),
    ('STREET', 'Đông Thạnh 7-1', 'dong thanh 7-1'),
    ('STREET', 'Đông Thạnh 7-1-1', 'dong thanh 7-1-1'),
    ('STREET', 'Đông Thạnh 7-2', 'dong thanh 7-2'),
    ('STREET', 'Đông Thạnh 7-4A', 'dong thanh 7-4a'),
    ('STREET', 'Đông Thạnh 7-5', 'dong thanh 7-5'),
    ('STREET', 'Đặng Thúc Vịnh', 'dang thuc vinh'),
    ('STREET', 'Đặng Thị Son', 'dang thi son'),
    ('STREET', 'Ấp Tam Đông 2', 'ap tam dong 2'),
    ('STREET', 'Ấp Đông 1-2', 'ap dong 1-2'),
    ('STREET', 'Ấp Đông 3', 'ap dong 3'),
    ('STREET', 'Ấp Đông 4', 'ap dong 4'),
    ('STREET', 'Ấp Đông 4-1', 'ap dong 4-1'),
    ('STREET', 'Ấp Đông 4-2', 'ap dong 4-2'),
    ('STREET', 'Ấp Đông 4-3', 'ap dong 4-3'),
    ('STREET', 'Ấp Đông 4-4', 'ap dong 4-4'),
    ('STREET', 'Ấp Đông 4-4C', 'ap dong 4-4c'),
    ('STREET', 'Ấp Đông 4-5', 'ap dong 4-5'),
    ('STREET', 'Ấp Đông 4-6', 'ap dong 4-6'),
    ('STREET', 'Ấp Đông 6', 'ap dong 6')
on conflict do nothing;

insert into streets (kind, parent_id, name, name_key)
select 'ALLEY', p.id, v.name, v.name_key from (values
    ('bui cong trung', 'Hẻm 149', 'hem 149'),
    ('nguyen thi pha', 'Hẻm 69', 'hem 69'),
    ('nguyen thi sang', 'Hẻm 40', 'hem 40'),
    ('nguyen anh thu', 'Hẻm 743', 'hem 743'),
    ('nguyen anh thu', 'Hẻm 885', 'hem 885'),
    ('pham thi giay', 'Hẻm 81', 'hem 81'),
    ('pham thi giay', 'Hẻm 84', 'hem 84'),
    ('thoi tam thon 17', 'Hẻm 156', 'hem 156'),
    ('thoi tam thon 17', 'Hẻm 158', 'hem 158'),
    ('thoi tam thon 17', 'Hẻm 2', 'hem 2'),
    ('thoi tam thon 17', 'Hẻm 37', 'hem 37'),
    ('thoi tam thon 17', 'Hẻm 37/1', 'hem 37/1'),
    ('tran thi boc', 'Hẻm 44', 'hem 44'),
    ('trinh thi mieng', 'Hẻm 46', 'hem 46'),
    ('trinh thi mieng', 'Hẻm 60', 'hem 60'),
    ('trinh thi mieng', 'Hẻm 64', 'hem 64'),
    ('to ky', 'Hẻm 19', 'hem 19'),
    ('dong thanh 2-6', 'Hẻm 281', 'hem 281'),
    ('ap dong 6', 'Hẻm 12', 'hem 12'),
    ('ap dong 6', 'Hẻm 20', 'hem 20')
) v (parent_key, name, name_key)
join streets p on p.parent_id is null and p.name_key = v.parent_key
on conflict do nothing;

insert into street_areas (street_id, area_id)
select s.id, a.id from (values
    ('bui cong trung', '', 'AP41'),
    ('bui cong trung', '', 'AP42'),
    ('bui cong trung', '', 'AP46'),
    ('bui cong trung', '', 'AP47'),
    ('bui cong trung', '', 'AP48'),
    ('bui cong trung', '', 'AP49'),
    ('bui cong trung', '', 'AP50'),
    ('bui cong trung', '', 'AP51'),
    ('bui cong trung', '', 'AP52'),
    ('bui thi lung', '', 'AP07'),
    ('bui thi lung', '', 'AP08'),
    ('bui van ngu', '', 'AP01'),
    ('bui van ngu', '', 'AP02'),
    ('bo bao rach ben da', '', 'AP48'),
    ('huynh thi hai', '', 'AP02'),
    ('huynh thi na', '', 'AP25'),
    ('huynh thi na', '', 'AP26'),
    ('huynh thi na', '', 'AP29'),
    ('huynh thi na', '', 'AP31'),
    ('huynh thi na', '', 'AP32'),
    ('huynh thi na', '', 'AP33'),
    ('huynh thi xe', '', 'AP48'),
    ('huynh thi xe', '', 'AP49'),
    ('kenh tran quang co', '', 'AP15'),
    ('le thi thin', '', 'AP44'),
    ('le thi thin', '', 'AP45'),
    ('le thi thin', '', 'AP46'),
    ('le van khuong', '', 'AP36'),
    ('le van khuong', '', 'AP37'),
    ('le van khuong', '', 'AP38'),
    ('le van khuong', '', 'AP39'),
    ('le van khuong', '', 'AP42'),
    ('le van khuong', '', 'AP43'),
    ('le van khuong', '', 'AP44'),
    ('nguyen thi be', '', 'AP33'),
    ('nguyen thi be', '', 'AP34'),
    ('nguyen thi be', '', 'AP39'),
    ('nguyen thi bup', '', 'AP15'),
    ('nguyen thi chon', '', 'AP33'),
    ('nguyen thi chon', '', 'AP39'),
    ('nguyen thi de', '', 'AP38'),
    ('nguyen thi de', '', 'AP42'),
    ('nguyen thi de', '', 'AP43'),
    ('nguyen thi muc', '', 'AP36'),
    ('nguyen thi muc', '', 'AP44'),
    ('nguyen thi muc', '', 'AP45'),
    ('nguyen thi nghe', '', 'AP08'),
    ('nguyen thi nghe', '', 'AP09'),
    ('nguyen thi nghe', '', 'AP21'),
    ('nguyen thi ngau', '', 'AP08'),
    ('nguyen thi ngau', '', 'AP18'),
    ('nguyen thi ngau', '', 'AP20'),
    ('nguyen thi ngau', '', 'AP21'),
    ('nguyen thi ngau', '', 'AP22'),
    ('nguyen thi ngau', '', 'AP23'),
    ('nguyen thi ngau', '', 'AP24'),
    ('nguyen thi pha', '', 'AP25'),
    ('nguyen thi pha', '', 'AP27'),
    ('nguyen thi pha', '', 'AP28'),
    ('nguyen thi pha', '', 'AP29'),
    ('nguyen thi sang', '', 'AP17'),
    ('nguyen thi sang', '', 'AP18'),
    ('nguyen thi sang', '', 'AP25'),
    ('nguyen thi sang', '', 'AP26'),
    ('nguyen thi sang', '', 'AP27'),
    ('nguyen thi sau', '', 'AP06'),
    ('nguyen thi sau', '', 'AP08'),
    ('nguyen thi sau', '', 'AP09'),
    ('nguyen thi sau', '', 'AP10'),
    ('nguyen thi sau', '', 'AP19'),
    ('nguyen thi sau', '', 'AP21'),
    ('nguyen thi thanh', '', 'AP16'),
    ('nguyen thi thanh', '', 'AP17'),
    ('nguyen thi thanh', '', 'AP18'),
    ('nguyen thi thanh', '', 'AP26'),
    ('nguyen thi tao', '', 'AP34'),
    ('nguyen thi tao', '', 'AP35'),
    ('nguyen thi tao', '', 'AP37'),
    ('nguyen thi tao', '', 'AP38'),
    ('nguyen thi ut', '', 'AP28'),
    ('nguyen thi ut', '', 'AP29'),
    ('nguyen thi ut', '', 'AP30'),
    ('nguyen thi ut', '', 'AP33'),
    ('nguyen thi ut', '', 'AP34'),
    ('nguyen thi ut', '', 'AP39'),
    ('nguyen thi diep', '', 'AP24'),
    ('nguyen thi diep', '', 'AP31'),
    ('nguyen thi diep', '', 'AP32'),
    ('nguyen thi det', '', 'AP45'),
    ('nguyen thi det', '', 'AP46'),
    ('nguyen anh thu', '', 'AP02'),
    ('nguyen anh thu', '', 'AP03'),
    ('nguyen anh thu', '', 'AP15'),
    ('nhanh sau do', '', 'AP48'),
    ('nhi binh 10a', '', 'AP50'),
    ('nhi binh 12', '', 'AP50'),
    ('nhi binh 14', '', 'AP51'),
    ('nhi binh 14', '', 'AP52'),
    ('nhi binh 15a', '', 'AP51'),
    ('nhi binh 15a', '', 'AP52'),
    ('nhi binh 16', '', 'AP51'),
    ('nhi binh 16', '', 'AP52'),
    ('nhi binh 17', '', 'AP51'),
    ('nhi binh 17', '', 'AP52'),
    ('nhi binh 19', '', 'AP51'),
    ('nhi binh 2', '', 'AP49'),
    ('nhi binh 2', '', 'AP50'),
    ('nhi binh 20a', '', 'AP50'),
    ('nhi binh 21', '', 'AP50'),
    ('nhi binh 22', '', 'AP49'),
    ('nhi binh 22', '', 'AP50'),
    ('nhi binh 26', '', 'AP48'),
    ('nhi binh 4', '', 'AP48'),
    ('nhi binh 5', '', 'AP48'),
    ('nhi binh 7', '', 'AP49'),
    ('nhi binh 8', '', 'AP49'),
    ('nhi binh 9', '', 'AP49'),
    ('nhi binh 9', '', 'AP50'),
    ('phung thi chuyen', '', 'AP06'),
    ('phung thi chuyen', '', 'AP10'),
    ('pham thi giay', '', 'AP04'),
    ('pham thi giay', '', 'AP05'),
    ('pham thi giay', '', 'AP11'),
    ('pham thi giay', '', 'AP14'),
    ('pham thi giay', '', 'AP16'),
    ('pham thi giay', '', 'AP17'),
    ('pham thi tom', '', 'AP43'),
    ('pham thi tom', '', 'AP45'),
    ('pham thi tom', '', 'AP46'),
    ('quang trung', '', 'AP06'),
    ('quang trung', '', 'AP11'),
    ('rach cau cut', '', 'AP51'),
    ('rach cau cut', '', 'AP52'),
    ('rach hai tap', '', 'AP48'),
    ('rach nhum', '', 'AP48'),
    ('rach tu hia', '', 'AP51'),
    ('soi do', '', 'AP48'),
    ('tam dong 1', '', 'AP09'),
    ('tam dong 1', '', 'AP21'),
    ('tam dong 11', '', 'AP17'),
    ('tam dong 11', '', 'AP18'),
    ('tam dong 11', '', 'AP26'),
    ('tam dong 12', '', 'AP17'),
    ('tam dong 12', '', 'AP18'),
    ('tam dong 19', '', 'AP14'),
    ('tam dong 19', '', 'AP16'),
    ('tam dong 19', '', 'AP18'),
    ('tam dong 20', '', 'AP14'),
    ('tam dong 20', '', 'AP16'),
    ('tam dong 22', '', 'AP14'),
    ('tam dong 25', '', 'AP12'),
    ('tam dong 25', '', 'AP13'),
    ('tam dong 26', '', 'AP04'),
    ('tam dong 26', '', 'AP12'),
    ('tam dong 26', '', 'AP13'),
    ('thai thi men', '', 'AP48'),
    ('thai thi men', '', 'AP49'),
    ('thoi tam thon 10', '', 'AP20'),
    ('thoi tam thon 11a', '', 'AP06'),
    ('thoi tam thon 11a', '', 'AP07'),
    ('thoi tam thon 11b', '', 'AP06'),
    ('thoi tam thon 11b', '', 'AP10'),
    ('thoi tam thon 11c', '', 'AP06'),
    ('thoi tam thon 12bis', '', 'AP11'),
    ('thoi tam thon 12bis', '', 'AP12'),
    ('thoi tam thon 13', '', 'AP05'),
    ('thoi tam thon 13', '', 'AP11'),
    ('thoi tam thon 13', '', 'AP12'),
    ('thoi tam thon 13', '', 'AP18'),
    ('thoi tam thon 14', '', 'AP17'),
    ('thoi tam thon 14', '', 'AP18'),
    ('thoi tam thon 15', '', 'AP14'),
    ('thoi tam thon 15', '', 'AP16'),
    ('thoi tam thon 15', '', 'AP17'),
    ('thoi tam thon 16', '', 'AP14'),
    ('thoi tam thon 16', '', 'AP16'),
    ('thoi tam thon 16', '', 'AP18'),
    ('thoi tam thon 17', '', 'AP02'),
    ('thoi tam thon 17', '', 'AP03'),
    ('thoi tam thon 18', '', 'AP04'),
    ('thoi tam thon 18', '', 'AP05'),
    ('thoi tam thon 28', '', 'AP04'),
    ('thoi tam thon 28', '', 'AP13'),
    ('thoi tam thon 6', '', 'AP03'),
    ('thoi tam thon 6', '', 'AP14'),
    ('thoi tam thon 6', '', 'AP15'),
    ('thoi tam thon 7c', '', 'AP08'),
    ('thoi tam thon 7c', '', 'AP09'),
    ('thoi tam thon 7j', '', 'AP09'),
    ('thoi tam thon tuyen 2', '', 'AP22'),
    ('thoi tu 1', '', 'AP08'),
    ('thoi tu 1', '', 'AP09'),
    ('thoi tu 2', '', 'AP09'),
    ('thoi tu 2', '', 'AP10'),
    ('thoi tu 5', '', 'AP08'),
    ('thoi tam thon 9', '', 'AP19'),
    ('thoi tam thon 9', '', 'AP20'),
    ('thoi tam thon 9', '', 'AP21'),
    ('thoi tam thon 9', '', 'AP23'),
    ('trung dong 1', '', 'AP23'),
    ('trung dong 1', '', 'AP24'),
    ('trung dong 10', '', 'AP08'),
    ('trung dong 10', '', 'AP22'),
    ('trung dong 11', '', 'AP08'),
    ('trung dong 11', '', 'AP22'),
    ('trung dong 12', '', 'AP22'),
    ('trung dong 5', '', 'AP21'),
    ('trung dong 5', '', 'AP23'),
    ('trung dong 6', '', 'AP21'),
    ('trung dong 6', '', 'AP23'),
    ('trung dong 7', '', 'AP21'),
    ('trung dong 7', '', 'AP23'),
    ('trung dong 8', '', 'AP21'),
    ('trung dong 8', '', 'AP22'),
    ('trung dong 8', '', 'AP23'),
    ('truong thi trung', '', 'AP35'),
    ('truong thi trung', '', 'AP37'),
    ('truong thi trung', '', 'AP38'),
    ('truong thi trung', '', 'AP42'),
    ('truong thi trung', '', 'AP43'),
    ('tran khac chan', '', 'AP07'),
    ('tran quang co', '', 'AP26'),
    ('tran thi boc', '', 'AP06'),
    ('tran thi boc', '', 'AP07'),
    ('tran thi boc', '', 'AP08'),
    ('tran thi boc', '', 'AP09'),
    ('tran thi hon', '', 'AP51'),
    ('tran thi nam', '', 'AP03'),
    ('tran van danh', '', 'AP39'),
    ('trinh thi doi', '', 'AP27'),
    ('trinh thi doi', '', 'AP28'),
    ('trinh thi doi', '', 'AP36'),
    ('trinh thi doi', '', 'AP37'),
    ('trinh thi doi', '', 'AP39'),
    ('trinh thi doi', '', 'AP40'),
    ('trinh thi doi', '', 'AP41'),
    ('trinh thi doi', '', 'AP42'),
    ('trinh thi doi', '', 'AP43'),
    ('trinh thi doi', '', 'AP44'),
    ('trinh thi doi', '', 'AP45'),
    ('trinh thi doi', '', 'AP46'),
    ('trinh thi doi', '', 'AP47'),
    ('trinh thi mieng', '', 'AP01'),
    ('trinh thi mieng', '', 'AP02'),
    ('trinh thi mieng', '', 'AP03'),
    ('trinh thi mieng', '', 'AP04'),
    ('trinh thi mieng', '', 'AP08'),
    ('trinh thi mieng', '', 'AP09'),
    ('trinh thi mieng', '', 'AP10'),
    ('trinh thi mieng', '', 'AP12'),
    ('trinh thi mieng', '', 'AP13'),
    ('trinh thi mieng', '', 'AP14'),
    ('trinh thi mieng', '', 'AP18'),
    ('trinh thi mieng', '', 'AP19'),
    ('trinh thi mieng', '', 'AP21'),
    ('to ky', '', 'AP01'),
    ('to ky', '', 'AP04'),
    ('to ky', '', 'AP05'),
    ('to ky', '', 'AP11'),
    ('to ky - nga ba tam dong', '', 'AP04'),
    ('to ky 12', '', 'AP05'),
    ('vo thi lung', '', 'AP31'),
    ('vo thi lung', '', 'AP32'),
    ('vo thi toi', '', 'AP28'),
    ('vo thi toi', '', 'AP35'),
    ('vo thi toi', '', 'AP36'),
    ('vo thi toi', '', 'AP37'),
    ('vo thi toi', '', 'AP38'),
    ('vo thi toi', '', 'AP39'),
    ('vo thi day', '', 'AP40'),
    ('vo thi day', '', 'AP48'),
    ('vo thi day', '', 'AP49'),
    ('de bao nhi binh 22', '', 'AP49'),
    ('de bao song sai gon', '', 'AP52'),
    ('dong thanh 1-3', '', 'AP27'),
    ('dong thanh 1-3', '', 'AP28'),
    ('dong thanh 1-3', '', 'AP29'),
    ('dong thanh 1-4', '', 'AP25'),
    ('dong thanh 1-4', '', 'AP27'),
    ('dong thanh 1-4', '', 'AP28'),
    ('dong thanh 1-4', '', 'AP29'),
    ('dong thanh 1-5', '', 'AP24'),
    ('dong thanh 2-2', '', 'AP29'),
    ('dong thanh 2-3', '', 'AP24'),
    ('dong thanh 2-3', '', 'AP31'),
    ('dong thanh 2-3-1', '', 'AP24'),
    ('dong thanh 2-3-1', '', 'AP31'),
    ('dong thanh 2-6', '', 'AP29'),
    ('dong thanh 2-6', '', 'AP30'),
    ('dong thanh 2-7', '', 'AP25'),
    ('dong thanh 3-1', '', 'AP34'),
    ('dong thanh 3-1', '', 'AP39'),
    ('dong thanh 3-3-1', '', 'AP29'),
    ('dong thanh 3-3-1', '', 'AP30'),
    ('dong thanh 3-4', '', 'AP30'),
    ('dong thanh 3-4', '', 'AP34'),
    ('dong thanh 4-2', '', 'AP28'),
    ('dong thanh 4-2', '', 'AP34'),
    ('dong thanh 4-2', '', 'AP35'),
    ('dong thanh 4-2 nhanh 1', '', 'AP28'),
    ('dong thanh 4-2 nhanh 1', '', 'AP30'),
    ('dong thanh 4-2 nhanh 1', '', 'AP34'),
    ('dong thanh 6-4', '', 'AP43'),
    ('dong thanh 7-1', '', 'AP40'),
    ('dong thanh 7-1', '', 'AP47'),
    ('dong thanh 7-1-1', '', 'AP47'),
    ('dong thanh 7-2', '', 'AP47'),
    ('dong thanh 7-4a', '', 'AP46'),
    ('dong thanh 7-5', '', 'AP45'),
    ('dang thuc vinh', '', 'AP06'),
    ('dang thuc vinh', '', 'AP10'),
    ('dang thuc vinh', '', 'AP11'),
    ('dang thuc vinh', '', 'AP12'),
    ('dang thuc vinh', '', 'AP18'),
    ('dang thuc vinh', '', 'AP19'),
    ('dang thuc vinh', '', 'AP20'),
    ('dang thuc vinh', '', 'AP24'),
    ('dang thuc vinh', '', 'AP25'),
    ('dang thuc vinh', '', 'AP29'),
    ('dang thuc vinh', '', 'AP30'),
    ('dang thuc vinh', '', 'AP31'),
    ('dang thuc vinh', '', 'AP33'),
    ('dang thuc vinh', '', 'AP34'),
    ('dang thuc vinh', '', 'AP35'),
    ('dang thuc vinh', '', 'AP38'),
    ('dang thuc vinh', '', 'AP39'),
    ('dang thuc vinh', '', 'AP40'),
    ('dang thuc vinh', '', 'AP41'),
    ('dang thuc vinh', '', 'AP42'),
    ('dang thi son', '', 'AP51'),
    ('ap tam dong 2', '', 'AP14'),
    ('ap dong 1-2', '', 'AP15'),
    ('ap dong 3', '', 'AP01'),
    ('ap dong 3', '', 'AP02'),
    ('ap dong 3', '', 'AP03'),
    ('ap dong 4', '', 'AP02'),
    ('ap dong 4-1', '', 'AP02'),
    ('ap dong 4-2', '', 'AP02'),
    ('ap dong 4-3', '', 'AP02'),
    ('ap dong 4-4', '', 'AP02'),
    ('ap dong 4-4c', '', 'AP02'),
    ('ap dong 4-5', '', 'AP02'),
    ('ap dong 4-6', '', 'AP02'),
    ('ap dong 6', '', 'AP01'),
    ('hem 149', 'bui cong trung', 'AP49'),
    ('hem 69', 'nguyen thi pha', 'AP30'),
    ('hem 40', 'nguyen thi sang', 'AP18'),
    ('hem 743', 'nguyen anh thu', 'AP03'),
    ('hem 885', 'nguyen anh thu', 'AP03'),
    ('hem 81', 'pham thi giay', 'AP04'),
    ('hem 84', 'pham thi giay', 'AP04'),
    ('hem 84', 'pham thi giay', 'AP13'),
    ('hem 156', 'thoi tam thon 17', 'AP03'),
    ('hem 158', 'thoi tam thon 17', 'AP02'),
    ('hem 158', 'thoi tam thon 17', 'AP03'),
    ('hem 2', 'thoi tam thon 17', 'AP03'),
    ('hem 37', 'thoi tam thon 17', 'AP03'),
    ('hem 37/1', 'thoi tam thon 17', 'AP03'),
    ('hem 44', 'tran thi boc', 'AP06'),
    ('hem 46', 'trinh thi mieng', 'AP02'),
    ('hem 60', 'trinh thi mieng', 'AP03'),
    ('hem 60', 'trinh thi mieng', 'AP04'),
    ('hem 64', 'trinh thi mieng', 'AP03'),
    ('hem 64', 'trinh thi mieng', 'AP04'),
    ('hem 19', 'to ky', 'AP01'),
    ('hem 281', 'dong thanh 2-6', 'AP29'),
    ('hem 12', 'ap dong 6', 'AP01'),
    ('hem 20', 'ap dong 6', 'AP01')
) v (name_key, parent_key, area_code)
join streets s on s.name_key = v.name_key and ((v.parent_key = '' and s.parent_id is null)
    or s.parent_id = (select p.id from streets p where p.parent_id is null and p.name_key = v.parent_key))
join areas a on a.code = v.area_code
on conflict do nothing;

insert into street_old_names (street_id, name, name_key, note)
select s.id, v.name, v.old_key, 'NQ 380/NQ-HĐND ngày 24/7/2025' from (values
    ('huynh thi xe', 'Nhị Bình 6', 'nhi binh 6'),
    ('le thi thin', 'Đông Thạnh 7', 'dong thanh 7'),
    ('nguyen thi be', 'Đường vào trường Trần Văn Danh', 'vao truong tran van danh'),
    ('nguyen thi chon', 'Đông Thạnh 2-5', 'dong thanh 2-5'),
    ('nguyen thi muc', 'Đông Thạnh 8', 'dong thanh 8'),
    ('nguyen thi nghe', 'Thới Tam Thôn 7', 'thoi tam thon 7'),
    ('nguyen thi tao', 'Đông Thạnh 4-1', 'dong thanh 4-1'),
    ('nguyen thi tao', 'Đông Thạnh 5', 'dong thanh 5'),
    ('nguyen thi ut', 'Đông Thạnh 3', 'dong thanh 3'),
    ('nguyen thi det', 'Đông Thạnh 7-4', 'dong thanh 7-4'),
    ('phung thi chuyen', 'Thới Tam Thôn 12', 'thoi tam thon 12'),
    ('pham thi tom', 'Đông Thạnh 7-3', 'dong thanh 7-3'),
    ('thai thi men', 'Nhị Bình 3', 'nhi binh 3'),
    ('truong thi trung', 'Đông Thạnh 6', 'dong thanh 6'),
    ('tran thi hon', 'Nhị Bình 15', 'nhi binh 15'),
    ('vo thi lung', 'Đông Thạnh 2-1', 'dong thanh 2-1'),
    ('vo thi toi', 'Đông Thạnh 4', 'dong thanh 4'),
    ('dang thi son', 'Nhị Bình 18', 'nhi binh 18')
) v (name_key, name, old_key)
join streets s on s.parent_id is null and s.name_key = v.name_key
on conflict do nothing;
